modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"
[[mods]]
modId="l2complements"
version="${file.jarVersion}" #mandatory
displayName="L2 Complements" #mandatory
logoFile="l2complements.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2complements]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2complements]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2complements]]
    modId="l2library"
    mandatory=true
    versionRange="[2.2.0,)"
    ordering="AFTER"
    side="BOTH"